# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'SogetiCertificates.p12'
    certPwd: 'sogeti'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: '3e96fa5b-66eb-42af-8d36-0343f328e4dd.mobileprovision'
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'AzureFirstApp'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
    signingOption: 'default'
    packageApp: true
